### PR TITLE
[colcon][tf2_py] fix catkin_symlink_install error in tf2_py

### PR DESCRIPTION
**Pull request by mqcmd196**
Fix the error 
```
CMake Error at catkin_symlink_install/catkin_symlink_install.cmake:157 (message):
  catkin_symlink_install_files() can't find
  '/home/obinata/ros1/src/geometry2/tf2_py/$<TARGET_FILE:tf2_py>'
Call Stack (most recent call first):
  catkin_symlink_install/catkin_symlink_install.cmake:325 (catkin_symlink_install_files)
  cmake_install.cmake:46 (include)


---
Failed   <<< tf2_py [3.24s, exited with code 1]
```
when built with colcon. Please see https://github.com/ros/geometry2/issues/486 for details

### CODE REVIEW

**Comment by paulbovbel** [comment]
+1 to this fix

**Comment by mqcmd196** [comment]
@v4hn Could you check it?

**Comment by v4hn** [comment]
This lay dormant in my inbox for quite a while... Oh god, who ever considered that generator expression a "fix" :exploding_head:

**Comment by v4hn** [comment]
Merged via cherry-pick.

I also created [a proper pull-request upstream](https://github.com/ros/geometry2/pull/567)

**Pull request closed without merging**
